<a href="https://colab.research.google.com/github/shiladityasarkar/QuantumComputing/blob/master/2348556_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Made by Shiladitya **2348556** with ❤️

## Installing libraries

In [44]:
%pip install qiskit_aer -q
%pip install qiskit -q
!pip install 'qiskit[visualization]' --quiet
!pip install pylatexenc --quiet

In [58]:
import numpy as np
from IPython.display import display

## Performing tensor product of two vectors

In [6]:
v1 = np.array([2, 5])
v2 = np.array([7, 10])
tensor_product = np.kron(v1, v2)
print("Tensor Product of v1 and v2:")
print(tensor_product)

Tensor Product of v1 and v2:
[14 20 35 50]


## Taking a Bell state as an example

In [47]:
from qiskit.quantum_info import Statevector, Operator
from numpy import sqrt

# a Bell state
initial_state = Statevector([1/sqrt(2), 0, 0, 1/sqrt(2)])
print("Initial state:")
initial_state.draw('latex')

Initial state:


<IPython.core.display.Latex object>

## Partial measurements ...

In [69]:
# Define a quantum operator (We choose the CNOT gate)
cnot_operator = Operator([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])

# Apply the operator to the state vector
final_state = cnot_operator @ initial_state

print("Final state:")
print(final_state, '\n\n')

# Performing partial measurement to get the probabilities of the first qubit being 0 or 1
probabilities = [
    abs(final_state.data[0])**2 + abs(final_state.data[1])**2,
    abs(final_state.data[2])**2 + abs(final_state.data[3])**2
]

print("State of the system after partial measurement:")
print("P(X=0):")
Statevector(probabilities[0]).draw('latex')

Final state:
Operator([[0.5+0.j, 0. +0.j, 0. +0.j, 0.5+0.j],
          [0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j],
          [0.5+0.j, 0. +0.j, 0. +0.j, 0.5+0.j],
          [0. +0.j, 0. +0.j, 0. +0.j, 0. +0.j]],
         input_dims=(2, 2), output_dims=(2, 2)) 


State of the system after partial measurement:
P(X=0):


<IPython.core.display.Latex object>

In [63]:
print("State of the system after partial measurement:")
print("P(X=1):")
Statevector(probabilities[1]).draw('latex')

Probabilities after partial measurement:
P(X=1):


<IPython.core.display.Latex object>

## CSWAP!

In [64]:
# Matrix representation of CSWAP gate
cswap_matrix = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1]
])

print("Matrix representation of CSWAP gate:")
print(cswap_matrix)


# Dirac notation of CSWAP gate
# CSWAP = |0><0| ⊗ I + |1><1| ⊗ SWAP
# where I is the identity operator and SWAP is the swap operator

# We can also write it as:
# CSWAP |abc> = |a><a| ⊗ I |abc> + |a><a| ⊗ SWAP |abc>
#             = |a><a| |abc> + |a><a| |bac>

# Here, |a>, |b>, |c> represent the states of the three qubits.

print("\nDirac notation of CSWAP gate:")
print("CSWAP = |0><0| ⊗ I + |1><1| ⊗ SWAP")

Matrix representation of CSWAP gate:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]]

Dirac notation of CSWAP gate:
CSWAP = |0><0| ⊗ I + |1><1| ⊗ SWAP


## Toffoli!

In [65]:
# Toffoli gate matrix representation
toffoli_matrix = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0]
])

print("Matrix representation of Toffoli gate:")
print(toffoli_matrix)


# Dirac notation of Toffoli gate
# Toffoli = |00><00| ⊗ I + |01><01| ⊗ I + |10><10| ⊗ I + |11><11| ⊗ X
# where I is the identity operator and X is the Pauli-X gate

print("\nDirac notation of Toffoli gate:")
print("Toffoli = |00><00| ⊗ I + |01><01| ⊗ I + |10><10| ⊗ I + |11><11| ⊗ X")

Matrix representation of Toffoli gate:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]

Dirac notation of Toffoli gate:
Toffoli = |00><00| ⊗ I + |01><01| ⊗ I + |10><10| ⊗ I + |11><11| ⊗ X


Thank you.